<?php return; ?>
	;------------------------------------------------
	;
	; Construc2 Main Configiguration.
	;
	;------------------------------------------------
	;  DO NOT EDIT THIS FILE !!
	;
	;  To override or add entires use a
	;  custom Theme configuration file.
	;------------------------------------------------

[cdn]
@default	= "ajax.googleapis.com"
	; -----
	; "Content Delivery Networks" for script libraries
	; also used for parameter field ./elements/cdnlist.php
	; You can add/merge/replace entries with a theme config
ajax.googleapis.com			= 1,jquery,mootools
ajax.aspnetcdn.com			= 0,jquery
code.jquery.com				= 1,jquery
cdnjs.cloudflare.com		= 1,jquery,mootools

[subst]
	; -----
	; LINK url placeholders
	; DO NOT REMOVE OR CHANGE ORDERING ANY THESE ENTRIES!
	;
media		= "{root}/media/system"
images		= "{root}/images"
template	= "{root}/templates/construc2"
theme		= "{template}/themes/{name}"

tmpl.css	= "{template}/css"
core.css	= "{template}/css/core"

system.css	= "{media}/css"
system.js	= "{media}/js"

	; "deprecated" - extension should use the media folder
module.css	= "{root}/modules/{name}/css"
module.js	= "{root}/modules/{name}/js"
plugin.css	= "{root}/plugins/{type}/{name}/css"
plugin.js	= "{root}/plugins/{type}/{name}/js"

[autocols]
column-1=0
column-2=0
column-3=0
column-4=0

[styleswitcher]
	; JS-based styleswitcher
@enabled	= 0

	; Replace or add to default switches? 0=no, 1=yes
@replace	= 1

	; Defaults than can be REPLACED with theme config files
	; Values are list labels run thru JText for translation
	; and best added to "xx-XX.override.ini"
@default	= normal
wireframe	= TPL_CONSTRUC2_STYLE_WIREFRAME
diagnostic	= TPL_CONSTRUC2_STYLE_DIAGNOSTIC_MODE
normal		= TPL_CONSTRUC2_STYLE_NORMAL_MODE

[fontscaler]
@enabled	= 0
	; -----
	; Font scaling
larger		= "Huge Font"
large		= "Large Font"
@default	= "Default Font"
small		= "Small Font"
smaller		= "Tiny Font"

[widgets]
	; -----
	; HTML Widgets supplied/activated by theme
date	= 1

[allow_empty]
	; -----
	; module types
custom	= 1

[features]
	; -----
	; stuff to be added on demand.
	; JS+CSS urls w/ optional {subst} keys
	; for dependencies use {features.feature-name}

form	= "{core.css}/forms.css"
editor	= "{features.form},{core.css}/edit-form.css"



